version: '3'
services:
  php:
    image: wishlist_php
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_port=9001 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=docker-dev"
    volumes:
      - .:/app
  nginx:
    image: nginx:1.17.3
    ports:
      - 8000:80
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./docker/my-db:/var/lib/mysql
