version: '3'
services:
  php:
    image: php_fpm
    volumes:
      - .:/app
  nginx:
    image: nginx:1.17.3
    ports:
      - 8000:80
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./docker/my-db:/var/lib/mysql
