version: '3'
services:
  php:
    image: php_fpm
    env_file:
      - '.env'
    volumes:
      - ..:/app
  nginx:
    image: nginx:1.17.3
    ports:
      - 8000:80
    volumes:
      - ..:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - '.env'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./my-db:/var/lib/mysql
